[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yt_dvr"
description = "A service to automatically record livestreams from various platforms, backed by yt-dlp"
version = "0.3"
authors = [{name = "JackMacWindows"}]
readme = "README.md"
license = "AGPL-3.0-or-later"
dependencies = [
    "yt_dlp",
    "quart",
    "pathvalidate",
    "typed-ffmpeg"
]

[project.optional-dependencies]
kick = [
    "kickpython",
    "python-dateutil",
    "yt_dlp[default,curl-cffi]"
]
youtube = [
    "pytchat",
    "python-dateutil"
]
rumble = [
    "httpx",
    "launchdarkly-eventsource[async]",
    "yt_dlp[default,curl-cffi]"
]

[project.scripts]
yt-dvr = "yt_dvr.__main__:main_cli"

[tool.setuptools.packages.find]
where = ["src"]
include = ["yt_dvr*"]

[tool.setuptools]
package-dir = {"" = "src"}
